<div class="jumbotron">
    <h1>Sobre o Projeto</h1>
    <p class="lead">
        Esse projeto consiste em uma simples Agenda de Contatos feita em 
        Zend Framework 2.
    </p>

    <h3>Ferramenta Utilizadas:</h3>
    <ul class="list-inline">
        <li><span class="label label-primary">Ubuntu 12.04</span></li>
        <li><span class="label label-primary">Zend Server</span></li>
        <li><span class="label label-primary">Zend Framework 2</span></li>
        <li><span class="label label-primary">ZFTool</span></li>
        <li><span class="label label-primary">Composer</span></li>
        <li><span class="label label-primary">Apache</span></li>
        <li><span class="label label-primary">VHOST</span></li>
        <li><span class="label label-primary">PHP 5.4</span></li>
        <li><span class="label label-primary">Servidor Interno PHP 5.4</span></li>
        <li><span class="label label-primary">NetBeans 7</span></li>
        <li><span class="label label-primary">Git</span></li>
        <li><span class="label label-primary">GitHub</span></li>
        <li><span class="label label-primary">Boostrap Twitter 3</span></li>
        <li><span class="label label-primary">jQuery</span></li>
        <li><span class="label label-primary">MySql</span></li>
    </ul>
</div>