<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Contato           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('contatos', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo">
                </div>
            </div>

            <div class="form-group">
                <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Tel. Principal:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="telefone_principal" class="form-control" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal">
                </div>
            </div>

            <div class="form-group">
                <label for="inputTelefoneSecundario" class="col-lg-3 col-md-3 control-label">Tel. Secundário:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="telefone_secundario" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Salvar Contato</button>
            <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>