<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Agenda de Contatos';
        echo $this
                ->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>

        <!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ;
        ?>
    </head>
    <body>
        <div class="container">
<div class="header">
    <ul class="nav nav-pills pull-right">
        <?php
        $url_home   = $this->url('home');
        $url_sobre  = $this->url('sobre');
        ?>
        <li <?php echo $this->menuAtivo($url_home); ?>>
            <a href="<?php echo $url_home; ?>">Início</a>
        </li>
        <li <?php echo $this->menuAtivo($url_sobre); ?>>
            <a href="<?php echo $url_sobre; ?>">Sobre</a>
        </li>
    </ul>
    <h3 class="text-muted"><?php echo $NAME_APPLICATION; ?></h3>
</div>

            <div class="row marketing">
                <?php echo $this->content; ?>
            </div>

            <div class="footer">
                <p class="muted credit pull-left">Company <a href="">© 2013</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="http://igorrocha.com.br">Igor Rocha</a>.</p>
            </div>
        </div>

        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;

        echo $this->inlineScript();
        ?>
    </body>
</html>